In [ ]:
from premise import *
import bw2data
from datapackage import Package
bw2data.projects.set_current("ei39")

ndb = NewDatabase(
    scenarios=[
        {"model": "image",
         "pathway": "SSP2-Base",
         "year": 2050},
    ],
    #years=[2005, 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100],
    #years=[2020, ],
    source_db="ecoinvent 3.9.1 cutoff", # <-- name of the database in the BW2 project. Must be a string.
    source_version="3.9", # <-- version of ecoinvent. Can be "3.5", "3.6", "3.7" or "3.8". Must be a string.
    key="tUePmX_S5B8ieZkkM7WUU2CnO8SmShwmAeWK9x2rTFo=",
)
ndb.update()
ndb.write_db_to_brightway()

In [1]:
from premise import *
import bw2data
from datapackage import Package
bw2data.projects.set_current("ei39")
ndb = PathwaysDataPackage(
    scenarios=[
        {"model": "image",
         "pathway": "SSP2-RCP19",
         "filepath": "/Users/romain/Library/CloudStorage/Dropbox/Notebooks/IAM-ecoinvent/new image/full data"
        },
    ],
    years=[2005, 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100],
    source_db="ecoinvent 3.9.1 cutoff", # <-- name of the database in the BW2 project. Must be a string.
    source_version="3.9", # <-- version of ecoinvent. Can be "3.5", "3.6", "3.7" or "3.8". Must be a string.
    #key="tUePmX_S5B8ieZkkM7WUU2CnO8SmShwmAeWK9x2rTFo=",
)

premise v.(2, 0, 1)
+------------------------------------------------------------------+
| Warning                                                          |
+------------------------------------------------------------------+
| Because some of the scenarios can yield LCI databases            |
| containing net negative emission technologies (NET),             |
| it is advised to account for biogenic CO2 flows when calculating |
| Global Warming potential indicators.                             |
| `premise_gwp` provides characterization factors for such flows.  |
| It also provides factors for hydrogen emissions to air.          |
|                                                                  |
| Within your bw2 project:                                         |
| from premise_gwp import add_premise_gwp                          |
| add_premise_gwp()                                                |
+------------------------------------------------------------------+
+-------------

In [2]:
ndb.create_datapackage(
    name="image-SSP2-RCP19",
    contributors=[
        {"name": "Romain",
        "email": "r_s at me.com",}
    ],
)

`update()` will skip the following sectors: 'buses', 'cars', 'two_wheelers'.
If you want to update these sectors, please run them separately afterwards.


Updating: external:  91%|██████████▉ | 10/11 [35:31<03:33, 213.11s/it]


External scenarios (datapackages) are not provided. Skipped.
Done!

Extracted 1 worksheets in 0.03 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Extracted 1 worksheets in 0.02 seconds
Remove uncertainty data.
Write new database(s) to matrix.
Running all checks...
Anomalies found: check the change report.
Running all checks...
Anomalies found: check the change report.
Running all checks...
Anomalies found: check the change report.
Mat

In [ ]:
from pathways import Pathways
p = Pathways(datapackage="./image-SSP2-RCP19/datapackage.json")

Solver: scikits.umfpack
Invalid datapackage: Descriptor validation error: {'path': 'mapping/mapping.yaml', 'profile': 'data-resource', 'name': 'mapping', 'format': 'yaml', 'mediatype': 'text/yaml', 'encoding': 'utf-8'} is not valid under any of the given schemas at "resources/45" in descriptor and at "properties/resources/items/oneOf" in profile
Invalid datapackage: Descriptor validation error: 'data-resource' is not one of ['tabular-data-resource'] at "resources/45/profile" in descriptor and at "properties/resources/items/properties/profile/enum" in profile


In [ ]:
import numpy as np
dp = p.calculate(
    methods=[
        'EF v3.1 - climate change - global warming potential (GWP100)',
        #'RELICS - metals extraction - Lithium',
    ],
    regions=[r for r in p.scenarios.coords["region"].values if r!="World"],
    #regions=["WEU",],
    scenarios=["SSP2-RCP19",],
    variables=[
        v for v in p.scenarios.coords["variables"].values
        if any(i in v for i in ["Industry", "Transport", "Heating"])
    ],
    years=[2005, 2010, 2020],
    characterization=True,
    #flows=["Lithium - natural resource - in ground - kilogram",],
    multiprocessing=False,
    demand_cutoff=0.01,
)

In [ ]:
import bw2calc as bc
import bw_processing as bwp

In [4]:
lca = bc.LCA(
    demand={1329: 1},
    data_objs=[dp],
)
lca.lci()
lca.lcia()
lca.score

/Users/romain/anaconda3/envs/pathways/lib/python3.11/site-packages/scikits/umfpack/umfpack.py:736: UmfpackWarning: (almost) singular matrix! (estimated cond. number: 1.21e+13)
  warnings.warn(msg, UmfpackWarning)


20.305023566997583

In [5]:
dp.data

[array([(    0,     0), (    0, 11778), (    0, 17244), ...,
        (36540, 21436), (36540, 19141), (36540, 24252)],
       dtype=[('row', '<i4'), ('col', '<i4')]),
 array([1.      , 0.012393, 0.002134, ..., 0.0025  , 0.00165 , 1.      ]),
 array([False,  True,  True, ...,  True,  True,  True]),
 array([(4461,     0), (4538,     0), (  92,     0), ..., (4681, 36486),
        (3744, 36486), (2417, 36486)],
       dtype=[('row', '<i4'), ('col', '<i4')]),
 array([6.67590000e-04, 8.51835000e-04, 7.53360000e-04, ...,
        9.28059118e-07, 2.32558140e-08, 1.30841121e-04]),
 array([(2687, 2687), (1572, 1572), (4590, 4590), (4658, 4658),
        (3665, 3665), (1607, 1607), (2221, 2221), (3681, 3681),
        (2462, 2462), (1779, 1779), (2278, 2278), ( 226,  226),
        (1361, 1361), (4077, 4077), (3655, 3655), (2703, 2703),
        (3510, 3510), (4378, 4378), (2957, 2957), ( 992,  992),
        (4122, 4122), (4089, 4089), (2253, 2253), ( 791,  791),
        (1073, 1073), (3507, 3507), (10

In [ ]:
arr = p.display_results()

In [ ]:
arr = arr.sum(dim="act_category")

In [ ]:
arr.to_netcdf('data.nc')

In [1]:
import xarray as xr

In [2]:
arr = xr.open_dataarray("data.nc")

In [142]:
import numpy as np
arr.loc[dict(year=[2015, 2025, 2035, 2045])] = np.nan

In [145]:
arr = arr.interpolate_na(dim="year")

In [147]:
arr = arr.interp(
    year=np.arange(arr.year.min(), arr.year.max() + 1,),
    kwargs={"fill_value": "interpolate"},
    method="linear",
)

In [148]:
df = arr.to_dataframe("value")

In [149]:
len(df)

13372032

In [150]:
df = df[df["value"]!=0.0]
df = df[~df["value"].isnull()]

In [151]:
len(df)

1215571

In [152]:
df=df.reset_index()

In [153]:
df.head()

variable  year region  \
0  Industry_Food and Tobacco_Electricity  2005    BRA   
1  Industry_Food and Tobacco_Electricity  2005    BRA   
2  Industry_Food and Tobacco_Electricity  2005    BRA   
3  Industry_Food and Tobacco_Electricity  2005    BRA   
4  Industry_Food and Tobacco_Electricity  2005    BRA   

                            location  model    scenario  \
0  Europe, without Russia and Turkey  image  SSP2-RCP19   
1                                 TZ  image  SSP2-RCP19   
2                              IN-DL  image  SSP2-RCP19   
3                              BR-TO  image  SSP2-RCP19   
4                                 MR  image  SSP2-RCP19   

                                     impact_category         value  
0  EF v3.1 - climate change - global warming pote...  1.043825e+06  
1  EF v3.1 - climate change - global warming pote...  1.149504e+06  
2  EF v3.1 - climate change - global warming pote...  1.264347e+04  
3  EF v3.1 - climate change - global warming pote...  1.652670e+02  
4  EF v3.1 - climate change - global warming pote...  1.881197e+03

In [154]:
df["year"].unique()

array([2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026,
       2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037,
       2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048,
       2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059,
       2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070,
       2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081,
       2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092,
       2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100])

In [155]:
from premise.geomap import Geomap
geo = Geomap("image")

In [156]:
d = {
    loc: geo.ecoinvent_to_iam_location(loc)
    for loc in df["location"].unique()
}

In [157]:
df["region from"] = df["location"].map(d)

In [158]:
df = df.drop('location', axis=1)

In [159]:
df = df.groupby([
    'variable', 'year', 'region', 'model', 'scenario', 'impact_category', 'region from'
]).sum().reset_index()

In [160]:
len(df)

125945

In [161]:
df["impact_category"] = df["impact_category"].str.replace("RELICS - metals extraction - ", "")
df["impact_category"] = df["impact_category"].str.replace("EF v3.1 - climate change - global warming potential (GWP100)", "climate change")

In [162]:
len(df)

125945

In [163]:
from pivottablejs import pivot_ui
from IPython.display import HTML
pivot_ui(df, outfile_path='pivottable_metals.html')

In [135]:
q = p.lca_results.sum(dim="act_category")

In [138]:
q.coords

Coordinates:
  * variable         (variable) <U49 19kB 'Industry_Food and Tobacco_Electric...
  * year             (year) int64 120B 2005 2010 2015 2020 ... 2080 2090 2100
  * region           (region) <U3 24B 'BRA' 'CAN'
  * location         (location) <U38 55kB 'BR-RN' ... 'CN-QH'
  * model            (model) <U5 20B 'image'
  * scenario         (scenario) <U10 40B 'SSP2-RCP19'
  * impact_category  (impact_category) <U60 480B 'EF v3.1 - climate change - ...

In [139]:
q.sel(
    impact_category='EF v3.1 - climate change - global warming potential (GWP100)',
    
).sum(dim=[
    "region",
    "location",
    "model",
    "scenario",
    "variable"
])

<xarray.DataArray (year: 15)> Size: 120B
array([4.66647340e+11, 5.45472829e+11, 0.00000000e+00, 5.78179822e+11,
       0.00000000e+00, 3.76307206e+11, 0.00000000e+00, 2.61900232e+11,
       0.00000000e+00, 2.25585623e+11, 2.05201143e+11, 1.67034370e+11,
       1.53310853e+11, 1.36826240e+11, 1.28377224e+11])
Coordinates:
  * year             (year) int64 120B 2005 2010 2015 2020 ... 2080 2090 2100
    impact_category  <U60 240B 'EF v3.1 - climate change - global warming pot...

In [164]:
[r for r in p.scenarios.coords["region"].values if r!="World"]

['BRA', 'CAN']